name: Runner Details

on:
  push:
    branches: [ main ]


jobs:
  Github-Runner-Specs:
    runs-on: ubuntu-latest

    steps:

      - name: OS Details
        run: hostnamectl

      - name: Disk
        run: df -Th

      - name: CPU
        run: lscpu

      - name: Apache2
        run: sudo systemctl restart apache2

      - name: IP
        run: curl ifconfig.io

      - name: port
        run: netstat -nltp
