name: Runner Details

on:
  push:
    branches: [ main ]


jobs:
  Github-Runner-Specs:
    runs-on: ubuntu-latest

    steps:

      - name: OS Details
        run: hostnamectl

      - name: Disk
        run: lsblk

      - name: CPU
        run: lscpu

      - name: Memory
        run: free -h
