name: Apache Restart Test

on: [push]

jobs:
  apache-test:
    runs-on: ubuntu-latest
    steps:
      - name: Update APT
        run: sudo apt-get update

      - name: Install Apache2
        run: sudo apt-get install apache2 -y

      - name: Restart Apache2
        run: sudo systemctl restart apache2

      - name: Check Apache Status
        run: systemctl status apache2 | head -n 10
