name: Apache Restart and Check

on: [push]

jobs:
  apache-check:
    runs-on: ubuntu-latest
    steps:
      - name: Update APT
        run: sudo apt-get update

      - name: Install Apache2
        run: sudo apt-get install apache2 -y

      - name: Restart Apache2
        run: sudo systemctl restart apache2

      - name: Check Apache status
        run: systemctl status apache2 | head -n 10

      - name: Check open ports with netstat
        run: sudo netstat -nltp || sudo ss -nltp

      - name: Curl localhost
        run: curl -I http://localhost
